# Site Info
title: 'ì•„ì›ƒìŠ¤íƒ ë”©ë³´ì´ ë¸”ë¡œê·¸'
tagline: 'ê°œë°œ, ê³µë¶€, ì¼ìƒ ë¸”ë¡œê·¸'
description: '<a href="http://github.com/outstanding1301" target="_blank">ì•„ì›ƒìŠ¤íƒ ë”©ë³´ì´</a>ì˜ ë¸”ë¡œê·¸ì…ë‹ˆë‹¤.'
baseurl: ""
url: http://outstanding1301.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: outstandingboy
  description: ê°œë°œì ì•„ì›ƒìŠ¤íƒ ë”©ë³´ì´ì˜ ê°œë°œ, ê³µë¶€ ë“±ë“± ìˆ˜ë¡
  contact:
    github:    https://github.com/outstanding1301
    email:     outstanding1301@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/categories/'
    # - { Categories: '/blog/categories/' }
    # - { TIL (Today I Learned): '/blog/categories/#til' }
    - { dev: '/blog/categories/#dev' }
    # - { Java: '/blog/categories/#java' }
    # - { Spring: '/blog/categories/#spring' }
    # - { git: '/blog/categories/#git' }
    - { etc: '/blog/categories/#etc' }
    # - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github: 
    - 'https://github.com/outstanding1301/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/kitten.jpg
  caption: Love cats. (and also dogs) ğŸ± ğŸ¶ â¤ï¸

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
